version: "3.8"

services:
  nodejs-sequelize:
    image: azeem-second-try
    command: sh -c "yarn install && yarn run dev"
    ports: 
      - 3001:3001
    working_dir: /Nodejs-Expressjs-Sequelize
    volumes: 
      - ./:/Nodejs-Expressjs-Sequelize
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Lmis@123
      MYSQL_DB: sequelize_test   

  mysql:
    image: mysql:8.0
    volumes: 
      - azeem-sequelize:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Lmis@123
      MYSQL_DATABASES: sequelize_test

volumes: 
  azeem-sequelize:    
